steps:
  # Step 1: Build the Spring Boot application
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['install']

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/load-393217/demo:$COMMIT_SHA', '.']

  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/load-393217/demo:$COMMIT_SHA']

  # Step 4: Deploy the application to Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/demo', 'demo=gcr.io/load-393217/demo:$COMMIT_SHA']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-east1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=ci-cd'
